// Generated by scripts/generate_sanitization_patterns.py. Do not edit by hand.
export const SANITIZATION_PATTERN_VERSION = 1;
export const SANITIZATION_PATTERN_DIGEST = "sha256:180b96049c785e204e69f6148ff1f80c5bc49955ce041c7f2e3adb3b023475f4";
export const SANITIZATION_MAX_SCAN_BYTES = 1048576;
export const SENSITIVE_FIELD_TOKENS = ["token","secret","password","cookie","authorization","pairing","private_key","private-key"] as const;
const PATTERN_SPECS: ReadonlyArray<{ id: string; regex: string; ignore_case: boolean }> = [{"id":"private_key","regex":"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----(?:[\\s\\S]{0,100000}?-----END (?:RSA |EC |OPENSSH )?PRIVATE KEY-----)?","ignore_case":false},{"id":"jwt","regex":"\\beyJ[A-Za-z0-9_-]{5,}\\.[A-Za-z0-9_-]{5,}\\.[A-Za-z0-9_-]{5,}\\b","ignore_case":false},{"id":"github_token","regex":"\\b(?:gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,})\\b","ignore_case":false},{"id":"anthropic_key","regex":"\\bsk-ant-[A-Za-z0-9_-]{20,}\\b","ignore_case":false},{"id":"openai_key","regex":"\\bsk-(?:proj-)?[A-Za-z0-9_-]{20,}\\b","ignore_case":false},{"id":"aws_access_key","regex":"\\b(?:AKIA|ASIA)[A-Z0-9]{16}\\b","ignore_case":false},{"id":"authorization","regex":"\\b(?:authorization|api[_-]?key|token|password|cookie)\\s*[:=]\\s*[^\\s,;]+","ignore_case":true},{"id":"connection_string","regex":"\\b(?:postgres(?:ql)?|mysql|mongodb(?:\\+srv)?|redis)://[^\\s]+","ignore_case":true},{"id":"cn_id","regex":"(?<!\\d)\\d{17}[0-9Xx](?!\\d)","ignore_case":false},{"id":"bank_card","regex":"(?<!\\d)(?:\\d[ -]?){15,18}\\d(?!\\d)","ignore_case":false}];
export const GENERATED_SECRET_PATTERNS: ReadonlyArray<readonly [string, RegExp]> = PATTERN_SPECS.map(
  (item) => [item.id, new RegExp(item.regex, item.ignore_case ? "gi" : "g")] as const,
);
