from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).parents[1]
SOURCE = ROOT / "guardd" / "sanitization" / "patterns.json"
TARGET = ROOT / "plugins" / "guard-openclaw" / "src" / "generated-sanitization-patterns.ts"


def main() -> None:
    document = json.loads(SOURCE.read_text(encoding="utf-8"))
    canonical = json.dumps(document, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    digest = "sha256:" + hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    specs = json.dumps(document["patterns"], ensure_ascii=False, separators=(",", ":"))
    tokens = json.dumps(document["sensitive_field_tokens"], ensure_ascii=False, separators=(",", ":"))
    target = f'''// Generated by scripts/generate_sanitization_patterns.py. Do not edit by hand.
export const SANITIZATION_PATTERN_VERSION = {int(document["version"])};
export const SANITIZATION_PATTERN_DIGEST = {json.dumps(digest)};
export const SANITIZATION_MAX_SCAN_BYTES = {int(document["max_scan_bytes"])};
export const SENSITIVE_FIELD_TOKENS = {tokens} as const;
const PATTERN_SPECS: ReadonlyArray<{{ id: string; regex: string; ignore_case: boolean }}> = {specs};
export const GENERATED_SECRET_PATTERNS: ReadonlyArray<readonly [string, RegExp]> = PATTERN_SPECS.map(
  (item) => [item.id, new RegExp(item.regex, item.ignore_case ? "gi" : "g")] as const,
);
'''
    TARGET.write_text(target, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
